enum OrderStatus {
  ORDER_CANCELED,
  ORDER_SHIPPED,
  ORDER_EN_ROUTE,
  ORDER_IN_SEPARATION,
  ORDER_STOCK_FAILED,
  ORDER_STOCK_RESERVED,
  PAYMENT_CONFIRMED,
  ORDER_CREATED,
}

export default OrderStatus;
